### ISSUE TITLE
docs: bdd_integration.rst page

### ISSUE THREAD

**Issue by jenisys** [Telefonica/toolium#103]
ON INSPECTION (reading the page):
First example for behave w/ hooks does not look correct to me (import-statement), like: ``toolium_before_all()`` function should be unknown because it is imported as ``before_all`` (and internally overwritten by the environment function).

HINT:
[Behave fixtures](http://behave.readthedocs.io/en/latest/fixtures.html) should also make the setup/teardown hooks easier to use.

**Comment by rgonalo** [comment]
The example works, `before_all()` from toolium lib is imported as `toolium_before_all()` and then called inside the `before_all()`of the user test project.
Anyway, I'll take a look at behave fixtures to use them in toolium initialization.
Thanks!
