### ISSUE TITLE
Installation fails due to conflicting selenium version

### ISSUE THREAD

**Issue by NeolithEra** [Telefonica/toolium#138]
Hi, users are unable to run toolium due to dependency conflict with _**selenium**_ package. 

As shown in the following full dependency graph of  toolium ,  toolium requires _**selenium >=2.53.6**_，while appium-python-client requires _**selenium<version range:>=3.14.1,<4**_.

According to pip’s “first found wins” installation strategy, _**selenium  4.0.0a1**_ is the actually installed version. However, _**selenium  4.0.0a1**_ does not satisfy _**>=3.14.1,<4**_.

### Dependency tree--
```
toolium<version range:>
| +-appium-python-client<version range:>=0.24>
| | +-selenium<version range:>=3.14.1,<4>
| +-behave<version range:==1.2.5>
| +-coverage<version range:==4.3.1>
| +-coveralls<version range:==1.1>
| +-docutils<version range:==0.14>
| +-lettuce<version range:==0.2.23>
| | +-fuzzywuzzy<version range:>
| | +-python-subunit<version range:>
| | +-sure<version range:>
| | | +-mock<version range:>
| | | +-six<version range:>
| +-mock<version range:==2.0.0>
| +-needle<version range:==0.5.0>
| +-pygments<version range:==2.2.0>
| +-pytest<version range:==2.9.2>
| +-requests<version range:>=2.12.4>
| +-requests-mock<version range:==1.2.0>
| +-screeninfo<version range:>
| +-selenium<version range:>=2.53.6>
| +-six<version range:>=1.10.0>
| +-sphinx<version range:==1.5.1>

```

### Solution
Could you change the version range of selenium from **_>=2.53.6_** to **_>=2.53.6,<4_**?

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
@rgonalo May I pull a request to fix this issue?

**Comment by rgonalo** [comment]
sure, you can pull the request, thanks!

**Comment by rgonalo** [comment]
Released a new version https://github.com/Telefonica/toolium/releases/tag/1.5.4 with your fix
