### ISSUE TITLE
config files extension normalized

### ISSUE THREAD

**Issue by Manzanero** [Telefonica/toolium#164]
"logging.conf" is the unique file with extension .conf while other uses .cfg by default

Shouldn't it use .cfg for all configuration files by default?

or both with:
'logging.cfg' if os.path.isfile(os.path.join(DriverWrappersPool.config_directory, 'logging.cfg')) else 'logging.conf'

**Comment by rgonalo** [comment]
Hi @Manzanero , 

The only reason for this difference is that usually the logger configuration file in python is `logging.conf` and the default extension for `ConfigParser` files is `.cfg`.
In any case, you can still use the same extension in your project for all files just setting logging config file before toolium `setUp`:

```py
from toolium import test_cases

class SeleniumTestCase(test_cases.SeleniumTestCase):
    def setUp(self):
        self.config_files.set_config_log_filename('logging.cfg')
        super(SeleniumTestCase, self).setUp()
```

Or setting the system property:
```py
os.environ['Config_log_filename'] = 'logging.cfg'
```

Best
Rubén
