### ISSUE TITLE
Is it possible to override settings of configuration file before browser session created

### ISSUE THREAD

**Issue by shortbloke** [Telefonica/toolium#165]
Hi,
Thanks for this useful library. I have a question I wonder if you could help answer.

I'm using the following code to provide a method of controlling the path to the configuration files:
```python
class TooliumSession(test_cases.SeleniumTestCase):
    """Toolium Session."""

    def setUp(self, configuration_directory=None):
        """Override setUp function to enable config file directory to be configured.

        :param configuration_directory: path to config file location
        """
        self.config_files.set_config_properties_filenames(
            "properties.cfg", "local-properties.cfg"
        )
        if configuration_directory:
            self.config_files.set_config_directory(str(configuration_directory))
        else:
            conf_dir = Path(getcwd(), "conf")
            if not Path.exists(conf_dir):
                conf_dir = Path(getcwd(), "draytekwebadmin", "conf")
            if Path.exists(conf_dir):
                self.config_files.set_config_directory(str(conf_dir))
        super(TooliumSession, self).setUp()
```

I'd also like to be able to set other properties programmatically, for example, the `type`, `gecko_driver_path`, `chrome_driver_path`, `headless` and perhaps other properties like wait durations. Allowing these to override settings that may be in the configuration file. 

I'm unclear if this is possible or how to go about it, as once the config file is read the session webdriver starts, which is too late. 

Any help/guidance gratefully received.
Martin

**Comment by rgonalo** [comment]
Hi Martin, 

Yes, it is possible to override the values read from the properties file just setting the desired value in the proper environment variable.
For instance to change the driver type, set `Driver_type` variable before toolium `setUp`:
`os.environ["Driver_type"] = 'chrome'`

Hope it helps!

**Comment by shortbloke** [comment]
Thanks, that did the trick!
