### ISSUE TITLE
is it possible to open 2 browsers?

### ISSUE THREAD

**Issue by DuXspace** [Telefonica/toolium#238]
I looked in code and didn't find a possibility to open 2 browsers, and i don't clearly understand how it initializing in test
secure_area = LoginPageObject().open().login(user)

**Comment by rgonalo** [comment]
Hi @DuXspace , 
A second browser can be opened and used this way:
```
second_wrapper = DriverWrapper()
second_wrapper.connect()
secure_area = LoginPageObject(second_wrapper).open().login(user)
```
as can be seen in https://toolium.readthedocs.io/en/latest/multiple_drivers.html#multiple-simultaneous-drivers

Besides this test shows an example opening two browsers:
https://github.com/Telefonica/toolium-examples/blob/master/web_behave/features/multiple_drivers.feature
https://github.com/Telefonica/toolium-examples/blob/master/web_behave/steps/multiple_drivers.py

**Comment by DuXspace** [comment]
Yep thank you! I have already found the same solution
