### ISSUE TITLE
Looks like it's not possible to use capabilities like "safari:useSimulator": True

### ISSUE THREAD

**Issue by DuXspace** [Telefonica/toolium#264]
I tried to use capabilities like there https://github.com/appium/appium-safari-driver and it looks like i can't add capabilities like safari:useSimulator to conf file.
The only way that i found it's adding them manually like:
driver_wrapper.config.set('AppiumCapabilities', 'safari:useSimulator', 'true')

Is there is any way to add this capability to conf file?

**Comment by rgonalo** [comment]
ConfigParser does not allow colon in a property name. To allow it in toolium, the colon must be replaced with '___' as explained in goog:loggingPrefs example in Chrome configuration: https://toolium.readthedocs.io/en/latest/browser_configuration.html#id3.
In your case, it should work with:

```
[AppiumCapabilities]
safari___useSimulator: true
```

**Comment by DuXspace** [comment]
Thank you for your response!
