### ISSUE TITLE
crop_element method in visual_test.py doesn't work properly

### ISSUE THREAD

**Issue by DuXspace** [Telefonica/toolium#288]
Hello! I tried to assert_screenshot for a local chromedriver and it doesn't crop it properly.

As i see the problem is in crop_element method in visual_test.py
Also it works the same for appium(android and ios drivers)

![page_logo](https://user-images.githubusercontent.com/6358686/167950056-c304e5a3-d2c9-4e46-8e6a-2533fa8dc674.png)

test file example:

from selenium.webdriver.common.by import By
from toolium.pageobjects.page_object import PageObject
from toolium.pageelements.page_element import PageElement

class BasicSite(PageObject):
    base_url = "https://www.basicwebsiteexample.com/"
    basic_site_logo = PageElement(By.ID, "page-zones__template-widgets__companyname-companyname")

def test_sample(driver_wrapper):
    driver_wrapper.driver.get(BasicSite.base_url)
    BasicSite().basic_site_logo.assert_screenshot("page_logo")

In test i used pytest_fixtures from toolium library.
In properties.cfg I also tried to add a browser settings like window_width and window_height, but it doesn't help

Maybe you have an idea how to solve that problem?

**Comment by DuXspace** [comment]
@rgonalo Hello, can you check it by cloning this simple project? https://github.com/DuXspace/issue-288 (I'm using toolium 2.6.0)
I have no idea why it works in that way, I have already tried local firefox/chrome/Android Chrome/iOS safari on 2 different macos(m1, intel) with different screen resolutions.
Also i tried to run it on remote selenoid server, and it works properly, looks like somehow coordinates of web_element is wrong for local running.

**Comment by rgonalo** [comment]
We have already found the source of the problem. It happens in Mac retina displays or other devices (Android/iOS) which pixel ratio is not 1. 
We will try to take the device pixel ratio in account when cropping elements in visaultesting, but in the meanwhile you could force in your tests the ratio to 1:

Chrome
```
[ChromeArguments]
force-device-scale-factor: 1
```
Firefox
```
[FirefoxPreferences]
layout.css.devPixelsPerPx: 1.0
```

**Comment by DuXspace** [comment]
@rgonalo Thank you very much for your help and help in solving the problem! But it won't to help for safari driver on iOS (https://appium.io/docs/en/drivers/safari/)

I thought a lot about just copying the visual testing file to our project, but due to the philosophy of the framework, which I really like, I would like this framework to be improved too.
Also there is a safari driver that does not support some selenium methods (commands), I would like to know one thing. Will you fix such things if I start creating tasks for these problems or if it is needed to be done by us.
I can create a list of problems and their solutions that we found and made on our side, I think this would be helpful for the universatility of the framework.

**Comment by rgonalo** [comment]
I would really appreciate that you become a toolium contributor. You can create the issues and fix them yourself or wait for us to solve them, but it would be faster if you push the solution.

**Comment by VladimirPodolyan** [comment]
@rgonalo @DuXspace Hi! Please take a look for [my fix](https://github.com/Telefonica/toolium/pull/290) when you have time and give me feedback is issue fixed or not.

**Comment by DuXspace** [comment]
@rgonalo Looks like all works properly, can you check it too and merge it?

**Comment by rgonalo** [comment]
I've just reviewed and merged it. Thanks for contributing @DuXspace @VladimirPodolyan

**Comment by VladimirPodolyan** [comment]
@rgonalo is it possible to roll out current dev version to pypi?
