### ISSUE TITLE
Support for Selenium 4 and Appium Python Client 2?

### ISSUE THREAD

**Issue by ricky-bhatia** [Telefonica/toolium#298]
Is there any plan to support selenium 4 and appium-python 2 versions?

**Comment by rgonalo** [comment]
Hi @ricky-bhatia, it is already in our backlog. We are going to start testing both versions in January.

**Comment by ricky-bhatia** [comment]
> Hi @ricky-bhatia, it is already in our backlog. We are going to start testing both versions in January.

Great! Thank you!

**Comment by randalb1991** [comment]
Thank You @rgonalo ! It is a great new :)

**Comment by rgonalo** [comment]
We are starting the update of toolium to support Selenium 4, stay tuned: https://github.com/Telefonica/toolium/pull/303

**Comment by ricky-bhatia** [comment]
> We are starting the update of toolium to support Selenium 4, stay tuned: #303

Hi @rgonalo , any update on this?

**Comment by rgonalo** [comment]
Hi @ricky-bhatia, we are still testing the changes, but we are publishing alpha versions of toolium 3 with the most basic needs: https://pypi.org/project/toolium/#history

Feedback is more than welcome!

**Comment by rgonalo** [comment]
Hi @ricky-bhatia and @randalb1991, toolium 3.0.0 is already available in pypi with Selenium 4 and Appium 2 support.
Enjoy!

**Comment by ricky-bhatia** [comment]
> Hi @ricky-bhatia and @randalb1991, toolium 3.0.0 is already available in pypi with Selenium 4 and Appium 2 support. Enjoy!

Great! Thanks @rgonalo
