### ISSUE TITLE
How to specify configuration when using Mobile Page Objects?

### ISSUE THREAD

**Issue by lambourn** [Telefonica/toolium#39]
I applied the Mobile Page Object pattern for iOS and Android (with base, android and ios folders) which works great.

Now, to make things more portable I need to load a specific driver configuration (ios or android) at runtime.

For now, when running a test on the command line I just set a environment variable and evaluate that in the setUp function. If it's `ios` I tell `config_files.set_config_properties_filenames` to load iOS specific config files (we currently use the default unittest framework, no pytest or nose)

Is this the way to go or is there some built-in logic?

**Comment by rgonalo** [comment]
For the moment it's the way to do it using unittest, pytest or nose.
In behave there is a built-in way:
`behave -D env=ios`

**Comment by lambourn** [comment]
ok, thanks. Actually I ported this pattern to my unittest files from the behave example in your docs ;-)

**Comment by rgonalo** [comment]
The system property *Config_environment* can be used to load specific config files. For example, if *Config_environment* value is *android*, Toolium configuration will be loaded from properties.cfg, android-properties.cfg and local-android-properties.cfg files:

`$ Config_environment=android nosetests web/tests/test_web.py`

`$ behave -D Config_environment=android`
