### ISSUE TITLE
Toolium output / report options

### ISSUE THREAD

**Issue by lambourn** [Telefonica/toolium#40]
When running tests, output is generated on the console and in the toolium.log

- toolium.log is a more generic log file and new output is appended to this file. 
- there is no default report file generated 

What's a preferred way of generating reports? Is this meant to be handled by the test framework used (unittest, pytest, etc.)? 

Are there any built-in report options other than logging and the visual test ouput?

**Comment by rgonalo** [comment]
You are right, test report is handled by the test framework (unittest, pytest, nose, behave ...) and toolium only generates logging file, error screenshots and visual report.

**Comment by lambourn** [comment]
ok, thanks
