### ISSUE TITLE
Restart driver when the test fail

### ISSUE THREAD

**Issue by jcanonav** [Telefonica/toolium#46]
I think that it's interesting the possibility to restart the selenium driver when the test fails and you have the reuse_driver option set to true. The most clear case is when you are logged in a website and your test fails (e.g. a lot of tests with login, validations and logout). In one error situation, the normal exit with a logout process is not performed and the next tests always fails because the login process always fails.
I use behave and solve this situation with a workaround in the bdd_common_after_scenario function:
```
    else:
        test_status = 'Fail'
        test_comment = "The scenario '{0}' has failed".format(scenario.name)
        context_or_world.logger.error(test_comment)
        # Capture screenshot and save logs on error
        DriverWrappersPool.capture_screenshots(scenario_file_name)
        DriverWrappersPool.save_all_webdriver_logs(scenario.name)

        ### Restart driver. Workaround
        # Read new configuration value -restart_fail-
        restart_driver_fail = context_or_world.toolium_config.getboolean_optional('Driver', 'restart_fail')
        if restart_driver_fail:
            # Close driver
            DriverWrappersPool.close_drivers_and_download_videos(scenario_file_name, status == 'passed', False)
            # Start "clean" driver
            create_and_configure_wrapper(context_or_world)
            connect_wrapper(context_or_world)
        ### End of workaround
```
Could be interesting add this functionality natively?

**Comment by rgonalo** [comment]
Hi @jcanonav, 
It's a good idea. I'll try to add this feature in DriverWrappersPool to allow using it in unittest, lettuce and behave tests.
Thanks!

**Comment by rgonalo** [comment]
I have added the property 'restart_driver_fail' in 'Driver' section to configure this behaviour
