### ISSUE TITLE
Reusing drive/ opening Anroid app without cache

### ISSUE THREAD

**Issue by NotSoShaby** [Telefonica/toolium#82]
I've implemented toolium into my tests and i've come across a very annoying problem (Appium issue).
When trying to open my android app without reinstalling the apk it deletes some of the app's data thus logging me out and makes me do the "first time in the app" tutorial. 

My trials to solve this included the following things:
* setting the `noReset ` to true in the desired capabilities
*setting the `fullReset ` to false in the desired capabilities
*opening the app with the correct activity

The only way I got it to work is to keep the driver running and do:
`driver.close_app()`
and then:
`driver.start_activity(app, activity)`

This means that I'll have to hold my driver throughout my tests.
So I went along and tried to find a way to reuse the driver on all my tests, but I noticed that toolium closes the driver in the `tearDownClass()` method.
![image](https://user-images.githubusercontent.com/26500236/32779496-afda0e46-c946-11e7-8df2-867e647a61b5.png)

I would really appreciate some help here. 

The best thing I could think of is starting up the driver and using toolium's setup but setting in the desired caps to just open the app without logging out from the user account and without having to go through the tutorial every time (I should mention that I used appium directly with all the params that I could think and got the same thing - so this is not a toolium bug, also - manually this does NOT happen).

If that won't be possible, I would like to find a way to keep the driver running between classes too and still use toolium's setup (because I use a lot of the toolium android\iOS functionality that won't work if I skip the setUp and just use the driver.)

Any suggestions/thoughts?

**Comment by rgonalo** [comment]
Using toolium as it is right now, driver can be reused in all tests of a class just adding in `properties.cfg`:
```
[Driver]
reuse_driver: true
```
But to reuse it in all tests of any class in your project, a new property should be added not to close the driver in `tearDownClass`.
I will try it and let you know when it is ready.

**Comment by NotSoShaby** [comment]
Thank you for the response. 
I can over-ride the tearDownClass in my testCase class to keep the driver open. 
I just wanted to make sure it won't have an unwanted affect on the setUp of the next test class.

**Comment by rgonalo** [comment]
No, there would be no problem with setUp, the driver will be used in all tests correctly. The only 'bad' effect is that the driver will not be closed after all tests.

**Comment by NotSoShaby** [comment]
Ok.. I'll handle closing the driver in the end of the suite.
Thanks

**Comment by rgonalo** [comment]
Now driver can be reused in all tests adding in `properties.cfg`:
```
[Driver]
reuse_driver_session = true
```
When using behave or pytest, the driver will be closed after all tests, but if you are using unittest, the driver will remain open after tests.
